#!/bin/bash
shopt -s expand_aliases
source $GOPATH/src/github.com/onosproject/onos-config/build/bash_aliases

$(dirname $0)/remove-devices >/dev/null 2>&1

echo "Press enter to add and provision leaf devices as peers..."
read foo

# Add our leaf devices, but as peers
set -x
ocli onos topo add device ec-wedge-65-1 --address 10.128.13.221:28000 --type Stratum --version 1.0.0 --plain --insecure --role peer --attributes="x=300,y=400"
ocli onos topo add device ec-wedge-65-2 --address 10.128.13.222:28000 --type Stratum --version 1.0.0 --plain --insecure --role peer --attributes="x=700,y=400"
set +x

echo "Press enter to add and provision spine device..."
read foo

# Add our spine
set -x
ocli onos topo add device ec-wedge-32 --address 10.128.13.223:28000 --type Stratum --version 1.0.0 --plain --insecure --role spine --attributes="x=500,y=200"
set +x

echo "Press enter to switch leaf devices to hybrid leaves..."
read foo

# Change leaves into hybrids
set -x
ocli onos topo update device ec-wedge-65-1 --role hybrid
ocli onos topo update device ec-wedge-65-2 --role hybrid
set +x

echo "Press enter to switch leaf devices peers to true leaves..."
read foo

# Change leaves into proper leaves
set -x
ocli onos topo update device ec-wedge-65-1 --role leaf
ocli onos topo update device ec-wedge-65-2 --role leaf
set +x
