#!/bin/bash
shopt -s expand_aliases
source $GOPATH/src/github.com/onosproject/onos-config/build/bash_aliases

ocli onos topo remove device wedge1
ocli onos topo remove device wedge2
ocli onos topo remove device wedge3

echo "Press enter to add and provision leaf devices as peers..."
read foo

# Add our leaf devices, but as peers
ocli onos topo add device wedge1 --address 10.128.13.221:28000 --type Stratum --version 1.0.0 --plain --insecure --role peer --attributes="x=300,y=400"
ocli onos topo add device wedge2 --address 10.128.13.222:28000 --type Stratum --version 1.0.0 --plain --insecure --role peer --attributes="x=700,y=400"

echo "Press enter to add and provision spine device..."
read foo

# Add our spine
ocli onos topo add device wedge3 --address 10.128.13.223:28000 --type Stratum --version 1.0.0 --plain --insecure --role spine --attributes="x=500,y=200"

echo "Press enter to switch leaf devices peers to true leaves..."
read foo

# Change leaves into proper leaves
ocli onos topo update device wedge1 --role leaf
ocli onos topo update device wedge2 --role leaf
