#!/bin/bash

export EXDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $EXDIR

onos-netcfg localhost demo-nodes-netcfg.json
onos-app localhost reinstall! onos-pipelines-fabric_2.2-SNAPSHOT_sde-8.9.1_simple.oar
onos-app localhost reinstall! fabric-plumber-1.0.oar

curl -X PUT -H "Content-type: application/json" --user onos:rocks http://localhost:8181/onos/v1/ui/preferences/onos/topo_zoom -d @ui-prefs-zoom.json
curl -X PUT -H "Content-type: application/json" --user onos:rocks http://localhost:8181/onos/v1/ui/preferences/onos/topo_prefs -d @ui-prefs-topo.json

