#!/bin/bash
shopt -s expand_aliases
source $GOPATH/src/github.com/onosproject/onos-config/build/bash_aliases

# Add our leaf devices, but as peers
set -x
ocli onos topo update device ec-wedge-65-1 --role ${1:peer}
ocli onos topo update device ec-wedge-65-2 --role ${1:peer}
