#!/bin/bash
shopt -s expand_aliases
source $GOPATH/src/github.com/onosproject/onos-config/build/bash_aliases

# Stage some files on the onos-cli node for creating roles, etc.
for r in none peer spine leaf hybrid; do
  echo "$r:"
  okctl cp $(dirname $0)/roles/$r.json $(okpid cli):/tmp
  ocli onos ztp remove role $r 1>/dev/null 2>&1
  ocli onos ztp add role /tmp/$r.json
done
